### ISSUE TITLE
Flutter web not working

### ISSUE THREAD

**Issue by Iampato** [marchdev-tk/flutter_google_maps#1]
## The logs
```
Unable to find modules for some sources, this is usually the result of either a                                    
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:flutter_google_maps/flutter_google_maps.dart';` from mbungedash|lib/main.dart at 2:1
       
```

## Flutter doctor
```
[✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.14.6 at /home/pato/development/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/pato/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-community/208
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[!] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server • web-javascript • Flutter Tools

```

**Comment by OlehMarchenko95** [comment]
Hi, @Iampato

I've got almost same configuration, and everything is working perfectly fine:

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version
    10.0.17763.1039], locale en-US)
    • Flutter version 1.14.6 at C:\Programming\flutter
    • Framework revision fabeb2a16f (7 weeks ago), 2020-01-28 07:56:51
      -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[√] Android toolchain - develop for Android devices (Android SDK version
    29.0.3)
    • Android SDK at C:\Programming\AndroidSDK
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Programming\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Oleh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

It would be great if you could provide sample of this issue!

Oh, by the way, I strongly recommend you to switch to **_dev_** channel, web on dev working better and faster than on beta channel.

**Comment by Iampato** [comment]
I fixed it by adding 
`build_runner` `build_web_compilers`
```
dev_dependencies:
  build_runner:
  build_web_compilers: 
  flutter_test:
    sdk: flutter
```

You should state this in the readme

**Comment by march-dev** [comment]
If you'll look into examples pubspec.yaml you'll see that there's no build_runner or build_web_compilers.

It's probably your local problem, imo you need to clear pub cache and reinstall flutter.
