### ISSUE TITLE
Make info window's text support multiline

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#11]
Currently if a text is long, it looks like this:
![image](https://user-images.githubusercontent.com/6189625/77253415-b35c8000-6c62-11ea-99e6-2909b3a64cfc.png)

Also `\n` symbol seems to be ignored. I see someone was interested in having dynamic height info window on iOS google maps library (https://stackoverflow.com/questions/44672663/dynamic-info-window-size-ios-google-maps), so I assume it's possible.

**Comment by march-dev** [comment]
`\n` symbol is ignored on all platforms.

This issue is related to #7. 
Widgets as a child will solve this problem. 

But for now, I've added `infoSnippet` String to `addMarker` method. This will allow to create 2 lines.

It's on pub, [3.6.0](https://pub.dev/packages/flutter_google_maps)
