### ISSUE TITLE
Option to specify icon size

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#12]
On 3.6.0 there is no option to specify icon size.

![image](https://user-images.githubusercontent.com/6189625/79051788-d9aa8580-7c3a-11ea-8aaf-b5554d96f8e1.png)

**Comment by march-dev** [comment]
For mobile there is no way to accomplish it.
But for web there is.

If you need only web implementation of it, please created new feature request.
