### ISSUE TITLE
add initial marker

### ISSUE THREAD

**Issue by dhs9004** [marchdev-tk/flutter_google_maps#16]
Hi, I was wondering how can add markers to the map when it is loading. something like this
```
GoogleMap(
markers: List<Marker>.of(),
....
)
```

**Comment by march-dev** [comment]
Hey, it's implemented in version [3.7.0 on pub](https://pub.dev/packages/flutter_google_maps)

**Comment by danielhdezs** [comment]
Hi thank you so much for add this to the project!!

I tried to use the initial marker but it is giving the following error, not sure if I'm missing something on the implementation.
 
![image](https://user-images.githubusercontent.com/46684523/82845566-51a6d500-9ea2-11ea-9d46-d910cd892c55.png)

Error
`E/flutter ( 6164): When an inherited widget changes, for example, if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget.`

Code
`  Widget build(BuildContext context) {

     _markers.add(Marker(
        GeoCoord(50.959088526141, -114.56634696970514),
        info: 'Test ',
        infoSnippet: 'Test info 2',
        icon: 'assets/images/map-marker-warehouse.png',
        onTap: (String test) async {          
          await showDialog(
            context: context,
            builder: (context) => AlertDialog(
              content: Text('This dialog was opened by tapping on the marker!',style: TextStyle(color: Colors.black),),
              actions: <Widget>[
                FlatButton(
                  onPressed: Navigator.of(context).pop,
                  child: Text('CLOSE'),
                ),
              ],
            ),
          );
        },
       ));

    return Stack(
      children: <Widget>[
        GoogleMap(
          key: _key,
          initialZoom: 10,
          initialPosition: GeoCoord(51.0447, -114.0719), // Calgary, AB
          mapType: MapType.roadmap,
          mapStyle: null,
          interactive: true,
          markers: _markers,
          // onTap: (coord) => _scaffoldKey.currentState.showSnackBar(SnackBar(
          //   content: Text(coord?.toString()),
          //   duration: const Duration(seconds: 2),
          // )),
          mobilePreferences: const MobileMapPreferences(
              trafficEnabled: false, myLocationEnabled: false),
          webPreferences: WebMapPreferences(
            fullscreenControl: true,
            zoomControl: true,
          ),
        ),

        
      ],
    );
  }
}`

Thanks,
