### ISSUE TITLE
Polygon clicked listener

### ISSUE THREAD

**Issue by joaquini** [marchdev-tk/flutter_google_maps#18]
## Use case
When you have a Polygon drawn in the map, it would be very useful to have the possibility to know when the user taps on the filled area. 

## Proposal

Let's suppose you have this Polygon drawn in the map and you make a click in that Polygon:
![image](https://user-images.githubusercontent.com/4087346/80557082-1cdf5500-89ac-11ea-850f-456b99ef5909.png)

Given that each Polygon has an id, it would be very useful to have the possibility of knowing that that Polygon was clicked. 
Then, when adding a Polygon to a Google Map, you could have some syntaxis like this:    
```
GoogleMap.of(_key).addPolygon(
    "Polygon ID",
    coordinatesList,
    onTap: (polygonId) {
        doSomethingWithPolygonId(polygonId);
    }
);
```

**Comment by march-dev** [comment]
Hey, it's implemented in version [3.7.0 on pub](https://pub.dev/packages/flutter_google_maps)
