### ISSUE TITLE
Make Marker listener aware of the Clicked Marker

### ISSUE THREAD

**Issue by joaquini** [marchdev-tk/flutter_google_maps#19]
## Use case
Pass the id of the current marker as a callback parameter when that marker is clicked.

## Proposal
Currently we have this:
```
GoogleMap.of(_key).addMarker(
  coord,
  label: "Some marker label",
  onTap: () {
    print("A marker was clicked");
  },
);
```

As you can see, we have no idea about what marker was clicked.
As I imagine, it would be very useful to have something like this:
```
GoogleMap.of(_key).addMarker(
  coord,
  label: "Some marker label",
  onTap: (markerId) {
    print("The marker $markerId was clicked");
  },
);
```

**Comment by march-dev** [comment]
Hey, it's implemented in version [3.7.0 on pub](https://pub.dev/packages/flutter_google_maps)
