### ISSUE TITLE
Android Marker Issue

### ISSUE THREAD

**Issue by mayavini** [marchdev-tk/flutter_google_maps#20]
While using marker icons, as per documentation the icon property should be a string containing file path to an image. In android device, getting the following error even after providing the path for a .bmp file for marker icon.
com.google.maps.api.android.lib6.common.apiexception.b: Failed to decode image. The provided image must be a Bitmap. 
Please provide an option to use BitMapDescriptor instead of string for icons.

**Comment by march-dev** [comment]
Hey, it's implemented in version [3.7.0 on pub](https://pub.dev/packages/flutter_google_maps).

You can use ByteString(<byte array>).toString() instead of path to an asset.

BitmapDescriptor cannot be added due to violation of cross-platform interface
