### ISSUE TITLE
The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by RageshAntony** [marchdev-tk/flutter_google_maps#26]
I am getting this error when running in Android (Web is fine)

```
 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14948): The following NoSuchMethodError was thrown building WebMap:
I/flutter (14948): The getter 'iterator' was called on null.
I/flutter (14948): Receiver: null
I/flutter (14948): Tried calling: iterator
I/flutter (14948): 
I/flutter (14948): The relevant error-causing widget was:
I/flutter (14948):   WebMap
I/flutter (14948):   file:///home/techrova/Documents/flutter_projects/flutter_complete_guide/lib/selectservice.dart:165:65
I/flutter (14948): 
I/flutter (14948): When the exception was thrown, this was the stack:
I/flutter (14948): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (14948): #1      GoogleMapState.initState (package:flutter_google_maps/src/mobile/google_map.state.dart:420:31)
I/flutter (14948): #2      StatefulElement._firstBuild 
..............................

```
```
import 'package:flutter/material.dart';
import 'package:flutter_google_maps/flutter_google_maps.dart';


GlobalKey<GoogleMapStateBase> _key = GlobalKey<GoogleMapStateBase>();

class WebMap extends StatelessWidget
{
 @override
Widget build(BuildContext context) => GoogleMap(
  key: _key,
  
);

}
```
I added the API Key in Android Manifest . Even the google_maps_flutter plugin working perfectly 

But I am getting error when using this plugin 

please help me  

I am using latest beta channel of flutter .. Device is Android Pie

**Comment by Chojecki** [comment]
You should add at least one marker in new version

**Comment by RageshAntony** [comment]
> You should add at least one marker in new version

Oohh Ok

I read the docs but can't understand how to add markers ... (what that .Of()??)

Please provide  a sample code 

Example Markers list (lat,lng)
(9.956719, 78.172637)
(9.908671, 78.149602)

**Comment by Chojecki** [comment]
You can just hardcode it like:

` GoogleMap(
              markers: {
                Marker(
                  GeoCoord(34.0469058, -118.3503948),
                ),
              },
...
`

I guess it's a bug. My friend spotted that in source code, it's iterating over the all markers, so if there's no any marker, app crash

**Comment by RageshAntony** [comment]
> You can just hardcode it like:
> 
> `GoogleMap( markers: { Marker( GeoCoord(34.0469058, -118.3503948), ), }, ...`
> 
> I guess it's a bug. My friend spotted that in source code, it's iterating over the all markers, so if there's no any marker, app crash
> 
> I did a PR for quick fix

Yeah working after adding a marker 

```
 Set<Marker> markers = new  Set(); 
   

 @override
Widget build(BuildContext context) {

markers.add(Marker( GeoCoord (9.956719, 78.172637)));
markers.add(Marker( GeoCoord (9.908671, 78.149602)));

   return GoogleMap(
  key: _key,
   markers: markers,
   initialPosition: GeoCoord(9.956719, 78.172637),
);
}

Thanks for your help 

It's better to add this in docs also 
```

**Comment by RageshAntony** [comment]
> You can just hardcode it like:
> 
> `GoogleMap( markers: { Marker( GeoCoord(34.0469058, -118.3503948), ), }, ...`
> 
> I guess it's a bug. My friend spotted that in source code, it's iterating over the all markers, so if there's no any marker, app crash
> 
> I did a PR for quick fix

One more question

How to show directions ?

I am getting Error :+1: 

```
 @override
Widget build(BuildContext context) {

markers.add(Marker( GeoCoord (9.956719, 78.172637)));
markers.add(Marker( GeoCoord (9.908671, 78.149602)));
var googleMap = GoogleMap(
  key: _key,
   markers: markers,
   initialPosition: GeoCoord(9.956719, 78.172637),
);
 GoogleMap.of(key).addDirection(GeoCoord(9.956719, 78.172637), GeoCoord(9.956719, 78.172637),    startLabel: '1',
              startInfo: 'Uthangudi',
              
              endInfo: 'Theppakulam',);
   return googleMap;
}
```
Error:

```
The following JSNoSuchMethodError was thrown building WebMap(dirty):
NoSuchMethodError: invalid member on null: 'currentState'

The relevant error-causing widget was:
  WebMap
  file:///home/techrova/Documents/flutter_projects/flutter_complete_guide/lib/selectservice.dart:165:65

```

**Comment by Chojecki** [comment]
Sorry I'm not maintainer of this package and don't have enough info/time to investigate those kind of errors. Maybe see the example project from repo or ask mainteiners

**Comment by march-dev** [comment]
Pull request merged
