### ISSUE TITLE
Marker Icon on android doesn't change

### ISSUE THREAD

**Issue by dhs9004** [marchdev-tk/flutter_google_maps#29]
Hi all, 

I have been trying to change the default marker Icon on android application, but it doesn't work. I tried the same configuration on web and it worked.

![image](https://user-images.githubusercontent.com/38137546/83949195-90f8ee00-a7df-11ea-8df3-de549cd9a939.png)

Thanks in advanced,

**Comment by dhs9004** [comment]
Any update on this?

I'm using this 
`_markerColor = 'assets/images/map-marker-clear.png';`

Do I have to use 'assets/images/image.png' as you description?

`If [icon] is set, must be a path to an image from project root as follows: assets/images/image.png. Or it must be an instance of [ByteString].`

**Comment by march-dev** [comment]
Look at example main file at line 137.
This is woking sample, checked.
