### ISSUE TITLE
Zoom functions & animateCamera when moveCamera

### ISSUE THREAD

**Issue by Pizzacorn** [marchdev-tk/flutter_google_maps#31]
## Proposal

There are two proposals:

**· When the camera move to new GeoCoords, it could do it smoothly and with zoom control.

· Function to zoomCamera (so we could replace the originals buttons by my own buttons).**

Example:

GoogleMap.of(_key).moveCamera(
        bounds,       
        animated: true,   //Not working, the camera just appear in the new bounds without animation.
        zoom: 14
);

GoogleMap.of(_key).zoomCamera(
        zoom: 14
);

**Comment by bobppsureway** [comment]
Agree! If the zoom level can be configured and moving with animation would be great. 
I think GoogleMap.of(_key).moveCamera() should take one GeoCoord() point as paramater not GeoCoordBounds.
I'm using 
 GoogleMap.of(_key).moveCamera(GeoCoordBounds(
                  southwest: geoPoint,
                  northeast: geoPoint));
Obviously it's not a good way.

**Comment by tomrozb** [comment]
The same here. Having the option to move with zoom change is a must, as most use cases requires zooming. Is there a plan for this feature?

**Comment by march-dev** [comment]
Done in [3.8.0](https://pub.dev/packages/flutter_google_maps)

**Comment by davidjan3** [comment]
> animated: true, //Not working, the camera just appear in the new bounds without animation.

This is still not working on web...
