### ISSUE TITLE
need  GroundOverlay function

### ISSUE THREAD

**Issue by aodbee** [marchdev-tk/flutter_google_maps#36]
need GroundOverlay, "flutter_google_maps" can be work ? 
Or  there anything that can be substituted?

rel
https://developers.google.com/android/reference/com/google/android/gms/maps/model/GroundOverlay

http://jsfiddle.net/bryan_weaver/4rxqQ/

**Comment by march-dev** [comment]
Hi @aodbee, this feature is not yet implemented in [google_maps_flutter](https://pub.dev/packages/google_maps_flutter).

You can substitude GroundOverlay with Marker.
