### ISSUE TITLE
Labels or inforwindow displayed by default

### ISSUE THREAD

**Issue by hackerunet** [marchdev-tk/flutter_google_maps#39]
Hi there, I'm wondering if is possible to show by default a label under or over the markers added programatically after google map is loaded?
Curently I'm trying to use the "label" parameter and I see nothing in the map after click on the marker, I just got the default infowindow with the text of info and infoSnippet, nothing more, so, I'm not very sure what's the label parameter for.
Thanks

**Comment by march-dev** [comment]
Hi, as per documentation **label** can be set only for **web**. It will draw what you put inside of the **label** in the center of the marker icon. This is default behavior for the web. For mobile it's not yet implemented by Google.
