### ISSUE TITLE
On click marker listener?

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#4]
Hey,
I think the plugin has a great potential. I need to open a new screen after a marker on the map is tapped. How can I set a onTap listener? I don't see any parameter in addMarker method.

**Comment by march-dev** [comment]
Hey,
It is implemented in version [3.2.0 on pub.dev](https://pub.dev/packages/flutter_google_maps)

**Comment by Gintasz** [comment]
@march-dev Great! How about onTap for an info window that opens on marker click?

**Comment by march-dev** [comment]
@Gintasz correct if I'm wrong, you need onTap callback if marker clicked for showing/hiding info window?

**Comment by Gintasz** [comment]
need onTap callback to be called when user taps on an info window that opens up when he tapped on the marker before.

**Comment by march-dev** [comment]
This changes are available with version [3.3.0 on pub](https://pub.dev/packages/flutter_google_maps)
