### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'animateCamera' was called on null.

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#6]
```
void fitCameraToMarkers(List<DbPhoto> entries)
  {
    var bounds = GeoCoordBounds(southwest: GeoCoord(entries.first.lat, entries.first.lng), northeast: GeoCoord(entries.first.lat, entries.first.lng));
    GoogleMap.of(_key).moveCamera(bounds, padding: 20, animated: true);
  }
```

Launching on iOS simulator, map loads fine, markers add fine, but when I call this method, I get

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'animateCamera' was called on null.
Receiver: null
Tried calling: animateCamera(Instance of 'CameraUpdate')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      GoogleMapState.moveCamera (package:flutter_google_maps/src/mobile/google_map.state.dart:57:19)
#2      _MapScreenState.fitCameraToMarkers (package:mapphotos/maincontent/map/MapScreen.dart:59:24)
#3      new _MapScreenState.<anonymous closure> (package:mapphotos/maincontent/map/MapScreen.dart:32:9)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#10     _PendingEvents.schedule.<anonymous c<…>
```

**Comment by Gintasz** [comment]
So GoogleMap.of(_key) returns not null after some time because this code makes it not crash:

```
void resetMapContent() async
  {
    if(viewModel.location.value != null)
    {
      var map = GoogleMap.of(_key);
      if(map == null)
      {
        return Future.delayed(Duration(milliseconds: 200), () {
          return this.resetMapContent();
        });
      }
      else
      {
        map.clearMarkers();
        var lat = viewModel.location.value.item1;
        var lng = viewModel.location.value.item2;

        map.addMarker(GeoCoord(lat, lng));

        setMapCameraToMarker();
      }
    }
  }
```

I also forgot to mention, that I was trying to call that function in OP on `afterFirstLayout` from `after_layout` library.

**Comment by march-dev** [comment]
My assumption is that the state of the GoogleMap is not yet created, so it might behave like this. I'm investigating this, and probably I'll add new method that will wait for state creation.

And if you need to move camera to specific location before map will be rendered, consider using GoogleMap.initialPosition property.

**Comment by Gintasz** [comment]
Will try initial position. It’s weird that it crashes on moveCamera, but if
I call addMarker few lines before moveCamera, it doesn’t crash on addMarker
line. They are both using the same maps instance.

**Comment by march-dev** [comment]
moveCamera uses GoogleMapController, that is lazy initialized by Google's GoogleMap, and other operations are standalone, they almost don't need nor Google's GoogleMap nor GoogleMapController.

**Comment by Gintasz** [comment]
How long do you think it will take? I have a deadline next week, hoping to
use your library.

**Comment by OlehMarchenko95** [comment]
Hey, fixed this issue in version [3.5.0 on pub](https://pub.dev/packages/flutter_google_maps)

**Comment by hackerunet** [comment]
Sorry, this behavior is still present, is there any way I can add a listener inside build of the part widget to know if Google Map was initialized and then add markers or do something else? I'm using 3.7.1

**Comment by nipunasudha** [comment]
> Sorry, this behavior is still present, is there any way I can add a listener inside build of the parent widget to know if Google Map was initialized and then add markers or do something else? I'm using 3.7.1

I was hoping to see a method like this. It may solve a lot of issues I have right now.
