### ISSUE TITLE
Image on info window

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#7]
Adding image of a Flutter's `Image` class on an infowindow, which opens after a marker is tapped, would be a nice feature. If you would add it, make sure lib accepts not a path of image but an object of class `Image`, so then network images can work too.

**Comment by march-dev** [comment]
**google_maps_flutter** plugin has only **title** and **subtitle** for **InfoWindow**.
On web it is possible to add ability to add an image, but without working mobile plugin, it's pointless for now.
For Web it could be done via **HTML String**.

**Comment by march-dev** [comment]
I've created feature request for this ability.
Here's the [link](https://github.com/flutter/flutter/issues/52878)

**Comment by march-dev** [comment]
Will create new issue when [#52878](https://github.com/flutter/flutter/issues/52878) will be closed.
