### ISSUE TITLE
onTap callback with tapped coords for map

### ISSUE THREAD

**Issue by Gintasz** [marchdev-tk/flutter_google_maps#9]
I'm opening a lot of issues here haha, but I support the idea of the plugin and think it will benefit the community greatly. What's really missing is an onTap callback for map, which would have a tapped coordinates object as a parameter. In my app there has to be a feature to select a location on map, so there is no other way to do that.

**Comment by march-dev** [comment]
Hey, it's implemented in version [3.4.0 on pub](https://pub.dev/packages/flutter_google_maps)
